remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Ashley Deibler's Professional Portfolio
description: Explore the projects I've worked on throughout my graduate program! 
